import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import { Providers } from "./provider";
import { Header } from "./header";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "find-dev",
  description: "Generated by create next app",
  icons: {
    icon: '/public/icon.png', // /public path
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="en" suppressHydrationWarning>
      <body className=
          "min-h-screen bg-background font-sans antialiased"
        >
       <Providers>
          <Header />
          <div className="container mx-auto">{children}</div>
        </Providers>
      </body>
    </html>
    </>
  );
}
